services:
  postgres:
    image: postgres:17.2
    container_name: postgres_17.2_customer2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer_backend
    environment:
      BACKEND_PORT: 5000
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SQL_PATH: /usr/src/app/customer.sql
      SQL_DATA_PATH: /usr/src/app/data.sql
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy 
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
